---
services:
  app:
    container_name: qrCodeApp
    image: vectorlab/fastapi-test-app:latest
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
    # volumes:
    #   - .:/app
    ports:
      - 5000:5000
    environment:
      - USE_HTTPS=0
    restart: always

