---
services:
  app:
    container_name: qrCodeApp
    # image: vectorlab/fastapi-test-app:latest
    image: python3.10:latest
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    networks:
        - proxy_network    
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
    # volumes:
    #   - .:/app
    ports:
      - 7000:5000
    environment:
      - USE_HTTPS=0
    restart: always

# This is only for deployied app
networks:
  proxy_network:
    name: vlAppsNetwork
    # Change this to "true" when deploying
    external: false